name: Update Team
description: Template for updating team information
title: "[Update Team]: "
labels: ["update", "team"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for your contribution! Please fill out the following information to help us understand your update.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a detailed description of the team changes.
      placeholder: Describe your changes here.
    validations:
      required: true 