name: Update Project
description: Template for updating project information
title: "[Update Project]: "
labels: ["update", "project"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for your contribution! Please fill out the following information to help us understand your update.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a detailed description of the project changes.
      placeholder: Describe your changes here.
    validations:
      required: true 