name: Other Update
description: Template for other types of updates
title: "[Update Other]: "
labels: ["update", "other"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for your contribution! Please fill out the following information to help us understand your update.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a detailed description of the changes.
      placeholder: Describe your changes here.
    validations:
      required: true 