name: deploy

on:
  pull_request:
    branches:
      - master

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.2"
          bundler-cache: true
      - name: Build with Jekyll
        run: bundle exec jekyll build --baseurl "127.0.0.1:8000"
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: site
          path: ./_site

  comment-artifact-link:
    runs-on: ubuntu-latest
    needs: build-and-upload
    steps:
      - name: Comment on PR
        uses: actions/github-script@v6
        with:
          script: |
            const artifactUrl = `https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts`;
            github.rest.issues.createComment({
              issue_number: ${{ github.event.pull_request.number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `The build artifact is available for download [here](${artifactUrl}).`
            });
