name: Pull Request

on:
  pull_request_target:
    branches:
      - master

permissions:
  pull-requests: write

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.2"
          bundler-cache: true
      - name: Build with Jekyll
        run: bundle exec jekyll build --baseurl "127.0.0.1:8000"
      - name: Upload artifact
        id: upload_artifact
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: ./_site
      - name: Comment on PR with artifact link
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            The build artifact is available for download [here](${{ steps.upload_artifact.outputs.artifact-url }}).
          comment-tag: artifact-link
